services:
  frontend:
    build: ./app/frontend
    ports:
      - "8000:80"
    depends_on:
      - api
    networks:
      - app_network

  api:
    build: ./app/api
    ports:
      - "5000:5000"
    depends_on:
      - core
    networks:
      - app_network

  core:
    build: ./app/core
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - api_data:/data
    ports:
      - "5001:5001"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - NODE_AUTH_TOKEN=secure_node_token_123
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3.13
    ports:
      - "5672:5672"
    networks:
      - app_network

  redis:
    image: redis:7.2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  api_data: